apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-local
  labels:
    argocd.zbialik.io/appset: kube-local
spec:
  generators:
  - git:
      repoURL: https://github.com/zbialik/kube-local.git
      revision: main
      directories:
      - path: k8s/*/*
  template:
    metadata:
      name: 'kube-local-{{path[1]}}-{{path[2]}}'
      labels:
        argocd.zbialik.io/app: '{{path[2]}}'
    spec:
      project: 'default'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        targetRevision: main
        repoURL: https://github.com/zbialik/kube-local.git
        path: '{{path}}'
      destination: 
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
